//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSistemaPesquisaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Acesso
    {
        public int LoginId { get; set; }
        public string Chave { get; set; }
        public string Senha { get; set; }
        public string Ativo { get; set; }
        public Nullable<int> PerfilId { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
    
        public virtual TB_Perfil TB_Perfil { get; set; }
    }
}
