//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSistemaPesquisaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MensagemEmail
    {
        public int TextoEmailId { get; set; }
        public Nullable<int> PesquisaId { get; set; }
        public string Mensagem { get; set; }
    
        public virtual TB_Pesquisa TB_Pesquisa { get; set; }
    }
}
