//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSistemaPesquisaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pesquisa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Pesquisa()
        {
            this.TB_Participantes = new HashSet<TB_Participantes>();
            this.TB_MensagemEmail = new HashSet<TB_MensagemEmail>();
            this.TB_PesquisaPerfil = new HashSet<TB_PesquisaPerfil>();
            this.TB_Questoes = new HashSet<TB_Questoes>();
            this.TB_VigenciaPesquisa = new HashSet<TB_VigenciaPesquisa>();
            this.TB_QuestaoEncadeada = new HashSet<TB_QuestaoEncadeada>();
            this.TB_VigenciaResposta = new HashSet<TB_VigenciaResposta>();
        }
    
        public int PesquisaId { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Participantes> TB_Participantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MensagemEmail> TB_MensagemEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PesquisaPerfil> TB_PesquisaPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Questoes> TB_Questoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VigenciaPesquisa> TB_VigenciaPesquisa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_QuestaoEncadeada> TB_QuestaoEncadeada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VigenciaResposta> TB_VigenciaResposta { get; set; }
    }
}
