//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSistemaPesquisaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Questoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Questoes()
        {
            this.TB_Alternativas = new HashSet<TB_Alternativas>();
            this.TB_Respostas = new HashSet<TB_Respostas>();
            this.TB_QuestaoEncadeada = new HashSet<TB_QuestaoEncadeada>();
        }
    
        public int QuestaoId { get; set; }
        public int PesquisaId { get; set; }
        public string Questao { get; set; }
        public int TipoRespostaId { get; set; }
        public Nullable<bool> Obrigatorio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Alternativas> TB_Alternativas { get; set; }
        public virtual TB_Pesquisa TB_Pesquisa { get; set; }
        public virtual TB_TipoResposta TB_TipoResposta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Respostas> TB_Respostas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_QuestaoEncadeada> TB_QuestaoEncadeada { get; set; }
    }
}
