//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSistemaPesquisaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QuestaoEncadeada
    {
        public int QuestaoEncadeadaId { get; set; }
        public Nullable<int> PesquisaId { get; set; }
        public Nullable<int> QuestaoId { get; set; }
        public Nullable<int> AlternativaId { get; set; }
        public Nullable<int> AcaoId { get; set; }
    
        public virtual TB_AcaoQuestaoEncadeada TB_AcaoQuestaoEncadeada { get; set; }
        public virtual TB_Alternativas TB_Alternativas { get; set; }
        public virtual TB_Pesquisa TB_Pesquisa { get; set; }
        public virtual TB_Questoes TB_Questoes { get; set; }
    }
}
