//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSistemaPesquisaFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_Respostas
    {
        public int RespostaId { get; set; }
        public int QuestaoId { get; set; }
        public int AlternativaId { get; set; }
        public string Resposta { get; set; }
        public int ParticipanteId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public virtual DateTime? DTER { get; set; }

        public virtual TB_Participantes TB_Participantes { get; set; }
        public virtual TB_Questoes TB_Questoes { get; set; }
       
        //public Nullable<bool> Obrigatorio { get; set; }
    }
}
