USE [master]
GO

/****** Object:  Database [DEV_PESQUISA_SATISFACAO2]    Script Date: 11/16/2018 4:01:50 PM ******/
CREATE DATABASE [DEV_PESQUISA_SATISFACAO2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DEV_PESQUISA_SATISFACAO2', FILENAME = N'H:\SQL_SERVICE\MSSQL11.SERVICE\MSSQL\DATA\DEV_PESQUISA_SATISFACAO2.mdf' , SIZE = 3328KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DEV_PESQUISA_SATISFACAO2_log', FILENAME = N'H:\SQL_SERVICE\MSSQL11.SERVICE\MSSQL\DATA\DEV_PESQUISA_SATISFACAO2.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DEV_PESQUISA_SATISFACAO2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET ANSI_NULLS ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET ANSI_PADDING ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET ARITHABORT ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET RECOVERY FULL 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET  MULTI_USER 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DEV_PESQUISA_SATISFACAO2] SET  READ_WRITE 
GO


